# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-25 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=3)),
                ('question_text', models.CharField(max_length=200)),
                ('choice_text', models.CharField(help_text='wybierz kierunek kluczowy', max_length=200)),
                ('vote', models.BooleanField(default=False)),
            ],
        ),
    ]
