# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-29 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klucz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_text',
        ),
        migrations.AlterField(
            model_name='question',
            name='branch',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice_text',
            field=models.CharField(max_length=200),
        ),
    ]
