# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-02 18:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('klucz', '0002_auto_20170629_2052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='vote',
        ),
    ]
